baseURL: "https://kayleebarrera.github.io" 
title: Kaylee Barrera - Undergraduate Astronomer

theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
        - name: Research
          url: research/

params:
    description: "I am an undergraduate student majoring in Planetary Science & Astronomy and Physics at MIT. I am interested in researching young exoplanets."
    author: Kaylee Barrera
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    footer_name: "Kaylee Barrera"
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: True
          title: Hi! I'm Kaylee Barrera.
          subtitle: 
              <span style="color:#052e80">*(she/they/he)*</span> <br><br>

              I am a final year undergraduate student double majoring in Planetary Science & Astronomy (EAPS) and Physics at MIT. 
              My research interests lie in detecting and characterizing exoplanets, particularly in young planetary systems.
              I currently work with [<span style="color:#052e80"><u>**Andrew Vanderburg**</u></span>](https://avanderburg.github.io/) and
              [<span style="color:#052e80"><u>**Sarah Blunt**</u></span>](https://sblunt.github.io/) on cross-validating Gaussian Process
              models of radial velocity measurements with [<span style="color:#052e80"><u>**eurydice**</u></span>](https://eurydice.readthedocs.io/en/latest/).<br><br>

              <span style="color:#d55672; display:inline-flex; align-items:center;margin-top:-100px;"><img src="email_icon.svg" alt="email icon" style="width:35px; height:35px; margin-left:-2px;margin-right:2px;">*kaybar [at] mit [dot] edu*</span>
          imageUrl: "doodle_portrait.png"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Kaylee Barrera
          buttons:
            - name: About
              url: about/
            - name: Research
              url: research/
            
    socialIcons:
        # - name: Email
        #   url: mailto:kaybar@mit.edu
        - name: CV
          url: kaylee_barrera_2025_CV.pdf
        - name: GitHub
          url: https://github.com/kayleebarrera
        - name: LinkedIn
          url: https://www.linkedin.com/in/kaylee-barrera/
        # - name: BlueSky
        #   url: https://bsky.app/profile/kayleebarrera.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kaylee Barrera"
      icon: pixel_kales.png
      iconHeight: 35

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2